### ISSUE TITLE
Gemini PR Serial broken in versions of Ubuntu newer than 10.04 LTS

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#1]
Plover 2.1.2 works properly in Ubuntu 10.04 LTS, but newer versions, including newer versions of Ubuntu 10 and Ubuntu 11.10 Classic, give the following error when Plover is run in the terminal and the "P" icon is pressed when protocol is set to Gemini PR:

Xlib.protocol.request.QueryExtension
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/plover/machine/geminipr.py", line 38, in run
    raw = self.serial_port.read(BYTES_PER_STROKE)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 439, in read
    if self.fd is None: raise portNotOpenError
AttributeError: 'Serial' object has no attribute 'fd'

Sidewinder X4 protocol works without any problems in all Ubuntu versions tested, but Gemini PR protocol seems only to work on Ubuntu 10.04.

(Mirabai's note: I'd noticed this bug several months ago, when my new computer, which I'd updated to a newer version of Ubuntu 10, stopped working with the PR protocol, even though my old computer, running Ubuntu 10.04 LTS, worked fine with Plover 2.1.2 in both Gemini and Sidewinder modes. I thought that possibly I'd screwed up some port settings on my new computer while trying to get Bluetooth working with an unpairable steno machine, but I just uninstalled Wubi and reinstalled with Ubuntu 11.10 Classic on my new computer, and I got the same result; Sidewinder protocol works fine, but Gemini PR gives the same error as above.)

---

Imported from Launchpad using lp2gh.
- date created: 2011-11-30T04:14:26Z
- owner: mkk-stenoknight
- assignee: joshua-harlan-lifton
- the launchpad url was https://bugs.launchpad.net/bugs/897998
